### ISSUE TITLE
OnlineStatsBase exports different `value` function than OnlineStats

### ISSUE THREAD

**Issue by meggart** [joshday/OnlineStatsBase.jl#14]
This leads to:

````julia
julia> using OnlineStatsBase, OnlineStats

julia> value
WARNING: both OnlineStats and OnlineStatsBase export "value"; uses of it in module Main must be qualified
ERROR: UndefVarError: value not defined
````

which is not so convenient

**Comment by joshday** [comment]
My apologies.  I released some changes and I thought OnlineStats had an upper bound on OnlineStatsBase.  Bear with me for a day or two.

**Comment by meggart** [comment]
Ok, thanks then I will just wait.

**Comment by joshday** [comment]
New OnlineStats release will be out momentarily!

https://github.com/JuliaRegistries/General/pull/10910
