### ISSUE TITLE
Enable precompilation

### ISSUE THREAD

**Issue by oschulz** [joshday/OnlineStatsBase.jl#2]
Enabling precompilation for OnlineStatsBase.jl (and OnlineStats.jl, eventually) would make it possible to use them as building blocks for larger packages that need precompilation themselves.

**Comment by joshday** [comment]
Good call.  done.

**Comment by oschulz** [comment]
Many thanks, @joshday! Will you enable precompilation for OnlineStats, too? Or is that more involved, since it's a more complex package?

**Comment by joshday** [comment]
Yes, I think everything upstream of OnlineStats is precompiled so I'll flip the switch for it.  I'm currently getting a better idea where things should live between OnlineStats/OnlineStatsBase.  I'll have new releases with both packages precompiled soon.

**Comment by oschulz** [comment]
Thanks, @joshday!
