### ISSUE TITLE
Extrema() only available for Date time types

### ISSUE THREAD

**Issue by brucala** [joshday/OnlineStatsBase.jl#20]
https://github.com/joshday/OnlineStatsBase.jl/blob/1737743cf6f88cf8644435a5a2a5efacf558f9c0/src/stats.jl#L196

As I understand from the code above, it looks like `Extrema()` only works for `Date` time types. Is there a reason for not extending to a generic `TimeType`?
For instance replacing the code to something like:
```
extrema_init(T::Type{<:TimeType}) = typemax(T), typemin(T), TimeType
```

**Comment by joshday** [comment]
> Is there a reason for not extending to a generic TimeType?

Only that my use case was for `Date` when I was implementing it.  

Fixed on master!  New release pending.  Thanks for the issue!
