### ISSUE TITLE
Generalize `Extrema` to keep `k` most extreme values (feature request)

### ISSUE THREAD

**Issue by goretkin** [joshday/OnlineStatsBase.jl#22]
For a given `k`, this is still `O(1)` with respect to the number of data.

It would look roughly like a streaming version of https://github.com/JuliaCollections/DataStructures.jl/blob/64cc58956c7ca2fb2c0600fb8431c62950250d34/src/heaps.jl#L100-L124

**Comment by joshday** [comment]
I like this idea.  I'll probably make it a different type.  `ExtremeValues`, `Tails`?

**Comment by goretkin** [comment]
` ExtremeValues` seems reasonable!

One design question (that I have in many different contexts in Julia) is whether `k` should be a type parameter or not. If it's a type parameter, it's reasonable to specialize on e.g. `k=1` so that `Extrema` could be deprecated and just aliased to something like `ExtremeValues{1}` at some point in the future.

**Comment by goretkin** [comment]
related:
https://github.com/Firionus/FastRunningMedian.jl
https://github.com/sairus7/SortFilters.jl

**Comment by joshday** [comment]
`ExtremeValues` now exists!
