### ISSUE TITLE
Handle transform errors in `FTSeries`

### ISSUE THREAD

**Issue by brucala** [joshday/OnlineStatsBase.jl#28]
# Motivation

A possible use of transformations in `FTSeries` is converting a stream of strings into a more appropriate type, e.g.:
```julia
> fit!(FTSeries(String, Mean(); transform=x->parse(Int, x)), string.(1:5))
FTSeries
└─ Mean: n=5 | value=3.0
```
but in real life it isn't uncommon that these streams can have some elements with a wrong or unexpected format, e.g.:
```julia
> fit!(FTSeries(String, Mean(); transform=x->parse(Int, x)), [string.(1:5); "6.0"])
ERROR: ArgumentError: invalid base 10 digit '.' in "6.0"
```

Within the vision of `FTSeries`, would it make sense to protect against failures of the transform?

# Possible solution

Below a possible solution with a `try-catch` approach, and keeping track of the number of failed transformations:
```julia
mutable struct FTSeries{IN, OS, F, T} <: StatCollection{IN}
    stats::OS
    filter::F
    transform::T
    nfiltered::Int
    nfailed::Int    <--- added to keep track of transform failures 
end
function FTSeries(stats::OnlineStat...; filter=x->true, transform=identity)
    IN, OS = Union{map(input, stats)...}, typeof(stats)
    FTSeries{IN, OS, typeof(filter), typeof(transform)}(stats, filter, transform, 0, 0)
end
function FTSeries(T::Type, stats::OnlineStat...; filter=x->true, transform=identity)
    FTSeries{T, typeof(stats), typeof(filter), typeof(transform)}(stats, filter, transform, 0, 0)
end
nobs(o::FTSeries) = nobs(o.stats[1]) + o.nfailed   <--- counting failed transformations as observations, although I'm not convinced this is the best approach
@generated function _fit!(o::FTSeries{N, OS}, y) where {N, OS}
    n = length(fieldnames(OS))
    quote
        if o.filter(y)
            try
                yt = o.transform(y)
                Base.Cartesian.@nexprs $n i -> @inbounds begin
                    _fit!(o.stats[i], yt)
                end
            catch e
                o.nfailed += 1
            end
        else
            o.nfiltered += 1
        end
    end
end
function _merge!(o::FTSeries, o2::FTSeries)
    o.nfiltered += o2.nfiltered
    o.nfailed += o2.nfailed
    _merge!.(o.stats, o2.stats)
end
```

I can make a PR with this solution If you think it makes sense.

**Comment by joshday** [comment]
I've become fond of wrapper types since you can compose them.  At some point I should change `FTSeries` to be `FilterTransform` wrapper type.

 How about something like this that tracks the `CountMap` of exceptions you run into?

```Julia
struct TryCatchStat{T, O<:OnlineStat{T}} <: OnlineStat{T}
    stat::O
    exceptions::CountMap{Exception}
end
TryCatchStat(stat::OnlineStat) = TryCatchStat(stat, CountMap(Exception))

nobs(o::TryCatchStat) = nobs(o.stat)

value(o::TryCatchStat) = value(o.stat)

function _fit!(o::TryCatchStat, y)
    try
        _fit!(o.stat, y)
    catch ex
        _fit!(o.exceptions, ex)
    end
end
```

**Comment by brucala** [comment]
oh, I think that's really smart!

With that proposal one would't just be keeping track of failed transformations like in my proposal, but also of any other possible exceptions. Following the `FTSeries` example, these extra exceptions could be for instance errors in the filter function call, cases where the type of the transformed input does't correspond to the expected type, ....

**Comment by joshday** [comment]
Doing a little bit of work on this and I'm liking how it's turning out:

```Julia

julia> o = TryCatch(FilterTransform(Mean(), String; transform = x -> parse(Int, x)))
TryCatch(FilterTransform(Mean)): n=0 | value=0.0

julia> fit!(o, "1")
TryCatch(FilterTransform(Mean)): n=1 | value=1.0

julia> fit!(o, "1.5")
TryCatch(FilterTransform(Mean)): n=1 | errors=1 | value=1.0

julia> OnlineStatsBase.errors(o)
OrderedCollections.OrderedDict{DataType, Int64} with 1 entry:
  ArgumentError => 1
```

**Comment by brucala** [comment]
I had a quick look at the new commit and it looks awesome :tada: 

Few comments came to mind, I'll leave few suggestions (even though the code is already merged) if I find some time later today.

**Comment by joshday** [comment]
Please do.  I haven't tagged a new release yet.

**Comment by brucala** [comment]
Left few suggestions. Things are already looking great, so feel free to ignore them

**Comment by brucala** [comment]
awesome! Makes sense to leave out the `GroupBy` suggestion... i liked the idea but it was a bit convoluted.

Did you push the changes?

**Comment by joshday** [comment]
Oops, they're pushed now
