### ISSUE TITLE
Improve doc ? value of type different from Float64 and from type of single observation value

### ISSUE THREAD

**Issue by femtotrader** [joshday/OnlineStatsBase.jl#37]
Hello,

I'm working on https://github.com/femtotrader/IncTA.jl/tree/OnlineStatsBase and I'm looking for a way to pass a candlestick as a single observation value.
My single observation value looks like

```julia
struct OHLCV{Ttime,Tprice,Tvol}
    open::Tprice
    high::Tprice
    low::Tprice
    close::Tprice
    volume::Tvol
    time::Ttime

    function OHLCV(
        open::Tprice,
        high::Tprice,
        low::Tprice,
        close::Tprice;
        volume::Tvol = missing,
        time::Ttime = missing,
    ) where {Ttime,Tprice,Tvol}
        new{Ttime,Tprice,Tvol}(open, high, low, close, volume, time)
    end

end
```

and I'm tring to calculate AccuDist and have "sufficient statistics" as a value of type Tprice (in this case it's Float64 but in general it can be different)

I did
```julia
"""
    AccuDist{T}()

The AccuDist type implements an Accumulation and Distribution indicator.
"""
mutable struct AccuDist{T} <: OnlineStat{T}
    value::Union{Missing,Float64}
    n::Int

    function AccuDist{T}() where {T}
        new{T}(missing, 0)
    end
end
```

and would like to do something like

```julia
mutable struct AccuDist{T, S} <: OnlineStat{T, S}
    value::Union{Missing, S}
    n::Int

    function AccuDist{T, S}() where {T, S}
        new{T, S}(missing, 0)
    end
end
=#

function OnlineStatsBase._fit!(ind::AccuDist, candle::OHLCV)
    ind.n += 1
    if candle.high != candle.low
        # Calculate MFI and MFV
        mfi =
            ((candle.close - candle.low) - (candle.high - candle.close)) /
            (candle.high - candle.low)
        mfv = mfi * candle.volume
    else
        # In case high and low are equal (division by zero), return previous value if exists, otherwise return missing
        ind.value = value(ind)
        return
    end

    if !has_output_value(ind)
        ind.value = mfv
    else
        ind.value = value(ind) + mfv
    end
end
```

Unfortunatly I have to use 

    value::Union{Missing,Float64}

I'd like to be able to do

    value::Union{Missing,Tprice}

How can I inherit OnlineStatsBase with OHLCV{Missing, Float64, Float64} as a single observation value and type Tprice as a sufficient statistics.

Maybe doc can slightly be improved on this side (and I could provide PR after understanding how to tackle that.

Especially in README example

```julia
using OnlineStatsBase

mutable struct MyMean <: OnlineStat{Number}
    value::Float64
    n::Int
    MyMean() = new(0.0, 0)
end
function OnlineStatsBase._fit!(o::MyMean, y)
    o.n += 1
    o.value += (1 / o.n) * (y - o.value)
end
```
value is type of Float64 but it could be more general I think (type of y, or an other type)

Some help from Julia guys experienced with types and inheritance could greatly help

Kind regards

**Comment by joshday** [comment]
Looking at your PR, you got most of the way there.  For a parametric type `B`, you can do something like this:

```Julia
struct A{T} <: OnlineStat{B{T}}
    value::T
end
```

I think this is a little too in-the-weeds to put in the README, but it would make sense somewhere in the OnlineStats docs.

**Comment by femtotrader** [comment]
thanks @joshday for your help.
