### ISSUE TITLE
Request for a new version to be tagged

### ISSUE THREAD

**Issue by MasonProtter** [joshday/OnlineStatsBase.jl#39]
Hi @joshday, can you tag a new version? The issue fixed in https://github.com/joshday/OnlineStatsBase.jl/commit/9b69dc182d1d3901f8c4da5793e378670291a980 is causing problems on some tests in Folds.jl

**Comment by joshday** [comment]
Didn't realize I was behind on my releases!  Should be in General soon: https://github.com/JuliaRegistries/General/pull/99619.

**Comment by MasonProtter** [comment]
Thanks!
